name 'alfresco'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@informatique.gov.pf'
license 'Apache 2.0'
description 'Installs/Configures alfresco'
long_description 'Installs/Configures alfresco'
version '0.1.1'

supports 'ubuntu', '= 14.04'
supports 'debian', '>= 7.7'

depends 'apt'
depends 'mysql', '~>5.6.1'
depends 'postgresql'
depends 'database', '~>2.3.1'
depends 'java'
depends 'tomcat'
depends 'ark'
depends 'apache2'
